version: '3.2'

services:
  freeradius:
    image: "freeradius/freeradius-server:latest"
    ports:
      - "1812:1812/udp"
    volumes:
      - "./clients.conf:/etc/raddb/clients.conf"
      - "./authorize:/etc/raddb/mods-config/files/authorize"
    restart: always